export const commonAppliancesList = [
  "Refrigerator",
  "LED TV",
  "Air Conditioner",
  "Washing Machine",
  "Electric Stove",
  "Microwave",
  "Desktop Computer",
  "Laptop",
  "Water Heater",
  "Dishwasher",
  "Hair Dryer",
  "Vacuum Cleaner",
  "Electric Kettle",
  "Ceiling Fan",
  "Wi-Fi Router",
  "Coffee Maker",
  "Toaster",
  "Blender",
  "Iron",
  "Electric Drill",
  "Other"
];

// You can also export default wattage values for common appliances
export const applianceWattages: Record<string, number> = {
  "Refrigerator": 150,
  "LED TV": 100,
  "Air Conditioner": 1500,
  "Washing Machine": 500,
  "Electric Stove": 2000,
  "Microwave": 1000,
  "Desktop Computer": 200,
  "Laptop": 50,
  "Water Heater": 3000,
  "Dishwasher": 1500,
  "Hair Dryer": 1800,
  "Vacuum Cleaner": 700,
  "Electric Kettle": 1200,
  "Ceiling Fan": 75,
  "Wi-Fi Router": 10,
  "Coffee Maker": 800,
  "Toaster": 850,
  "Blender": 400,
  "Iron": 1100,
  "Electric Drill": 800
};