import { useState } from "react";
import { Helmet } from "react-helmet";
import { ChevronDown, ChevronUp, ChevronRight } from "lucide-react";
import { Link } from "react-router-dom";

const faqs = [
  {
    question: "How does solar power work?",
    answer:
      "Solar panels convert sunlight into electricity using photovoltaic cells. This electricity can power your home or business, and excess energy can be stored or sent back to the grid.",
  },
  {
    question: "What is a hybrid solar system, and how does it work?",
    answer:
      "A hybrid solar system combines the features of both grid-tied and off-grid systems. It utilizes solar panels, a hybrid inverter, and battery storage. During the day, solar panels generate electricity to power your home and charge the batteries. Excess energy can be stored for later use or fed back into the grid. At night or during power outages, the system draws energy from the batteries, ensuring a continuous power supply. This setup offers energy independence and reliability, especially in areas with unstable grid power.",
  },
  {
    question: "What is a grid-tie solar system, and what are its benefits?",
    answer:
      "A grid-tie, or on-grid, solar system is connected directly to the public electricity grid. It doesn't require batteries, as it uses solar energy during the day and draws power from the grid when needed, such as at night. One of the main advantages is the ability to export excess solar energy back to the grid through net metering, earning credits that can offset your electricity bills. Grid-tie systems are cost-effective, have a faster return on investment, and are ideal for areas with reliable grid power.",
  },
  {
    question: "How much can I save with solar?",
    answer:
      "Most customers save 70-80% on their electricity bills after switching to solar. Actual savings depend on your energy usage and system size.",
  },
  {
    question: "What is the warranty on Sunphil Solar systems?",
    answer:
      "We offer an industry-leading 12-year warranty on our solar panels 5-year on inverters and 3-year on batteries, ensuring long-term peace of mind.",
  },
  {
    question: "How long does installation take?",
    answer:
      "Most residential installations are completed within 1-2 days, depending on system size and site conditions.",
  },
  {
    question: "Do I need batteries for my solar system?",
    answer:
      "Batteries are optional but recommended for backup power during outages and for maximizing your solar investment. We offer advanced LiFePO4 battery solutions.",
  },
  {
    question: "What is net metering and how does it benefit me?",
    answer:
      "Net metering allows you to sell excess electricity generated by your solar panels back to the grid. This results in credits on your electricity bill, further reducing your monthly expenses. It's a great way to maximize the return on your solar investment.",
  },
  {
    question: "How long do solar panels last?",
    answer:
      "High-quality solar panels typically come with a 25-year performance warranty and can function effectively for over 30 years with proper maintenance.",
  },
  {
    question: "Do solar panels require regular maintenance?",
    answer:
      "Solar panels are low-maintenance. It's recommended to clean them every 3-6 months to remove dust and debris. Additionally, having your system inspected annually ensures optimal performance.",
  },
  {
    question:
      "Can solar panels still generate electricity during cloudy or rainy days?",
    answer:
      "Yes, solar panels can still produce electricity during cloudy or rainy days, albeit at reduced efficiency. The Philippines averages about five hours of sunlight per day, making solar energy a viable option year-round.",
  },
  {
    question:
      "What is the difference between on-grid and off-grid solar systems?",
    answer:
      "An on-grid system is connected to the national power grid, allowing you to draw electricity when your solar system isn't producing enough, and to feed excess power back to the grid. An off-grid system operates independently and requires battery storage to supply power during non-sunny periods.",
  },
  {
    question: "Can I install solar panels on any type of roof?",
    answer:
      "Most roofs can accommodate solar panels, but factors like roof material, angle, and shading affect suitability. A professional assessment ensures optimal placement and performance.",
  },
  {
    question: "Is it possible to install solar panels in a condominium unit?",
    answer:
      "Installing solar panels in condominiums can be challenging due to shared roof spaces and structural considerations. It's more feasible for standalone homes or townhouses. However, some new developments may incorporate solar solutions during the design phase.",
  },
  {
    question:
      "What government incentives are available for solar energy users in the Philippines?",
    answer:
      "The Renewable Energy Act of 2008 offers incentives like net metering, income tax holidays for businesses, and zero VAT on renewable energy equipment. These benefits make solar energy more accessible and cost-effective.",
  },
];

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const toggle = (idx: number) => {
    setOpenIndex(openIndex === idx ? null : idx);
  };

  return (
    <div className="min-h-screen w-full bg-neutral-950">
      <div className="container mx-auto px-4 py-20">
        <Helmet>
          <title>FAQ | Sunphil Solar</title>
          <meta
            name="description"
            content="Frequently asked questions about solar installation, savings, and Sunphil Solar services."
          />
        </Helmet>
        {/* Breadcrumbs */}
        <nav aria-label="Breadcrumb" className="mb-6">
          <ol className="flex items-center space-x-2 text-sm text-white/80">
            <li>
              <Link to="/" className="flex items-center hover:text-blue-400">
                <svg
                  className="mr-2"
                  width="16"
                  height="16"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  viewBox="0 0 24 24"
                >
                  <path d="M3 9.75L12 4l9 5.75V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9.75Z" />
                  <path d="M9 22V12h6v10" />
                </svg>
                Home
              </Link>
            </li>
            <li className="flex items-center">
              <ChevronRight size={16} className="mx-1" />
              <span className="text-blue-400">FAQ</span>
            </li>
          </ol>
        </nav>
        <h1 className="text-4xl font-bold text-center mb-8 text-white">
          Frequently Asked Questions
        </h1>
        <div className="space-y-4">
          {faqs.map((faq, idx) => (
            <div
              key={idx}
              className="bg-white/10 backdrop-blur-lg rounded-lg shadow-elevation-1"
            >
              <button
                className="w-full flex justify-between items-center px-6 py-4 text-left text-lg font-semibold text-white focus:outline-none"
                onClick={() => toggle(idx)}
                aria-expanded={openIndex === idx}
                aria-controls={`faq-panel-${idx}`}
              >
                <span>{faq.question}</span>
                {openIndex === idx ? (
                  <ChevronUp className="w-5 h-5" />
                ) : (
                  <ChevronDown className="w-5 h-5" />
                )}
              </button>
              {openIndex === idx && (
                <div
                  id={`faq-panel-${idx}`}
                  className="px-6 pb-4 text-white/80 border-t border-white/10 animate-fadeIn"
                >
                  {faq.answer}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
